### ISSUE TITLE
Request: RSS feed

### ISSUE THREAD

**Issue by mtkidd** [VAheritage/xtf#10] opened 2021-05-20 15:38 UTC
If possible, I would like to have an RSS feed so that we can share the newest finding aids (or updated ones) via the feed and share on Twitter. I currently have an RSS feed set up using Politepol https://politepol.com/en/preview/127569. It uses the info from the Browse page with sort by set to "Date, Descending." It works ok, but it sorts alphabetically it isn't always picking up all the new uploads.  It also does not catch updated finding aids that have an earlier publishing date (e.g., if I update a FA originally published in 2017, it will not show up in the feed.)

This is a low priority and no worries if it isn't feasible.

**Comment by sdm7g** [comment] 2021-05-21 02:58
fixed dateStamp template. saxon:systemID() function appeared to not be returning file path as intended. 
replaced function with base-uri() .   
https://github.com/VAheritage/xtf/commit/a9070549674ac6919cdda336a2c1bfc8fffd5461

\

1. requires complete reindex (in process)
2. Need to add a search function : since( dateStamp )  
3. and appropriate formatting...

**Comment by sdm7g** [comment] 2021-05-21 04:54
If you append "&sort=rss" to the end of a search or browse URL, for example:
https://ead.lib.virginia.edu/vivaxtf/search?browse-all=yes&sort=rss
It will sort the results in order of newest file modification times.
This can be used with other search params or facets. 
I need to add this to the sort-by option on the results page.

**Comment by mtkidd** [comment] 2021-05-21 14:01
Thanks! That is helpful info.

**Comment by sdm7g** [comment] 2021-05-21 15:53
https://ead.lib.virginia.edu/vivaxtf/search?smode=browse&browse-all=yes&sort=rss

~~Note: sort order is date, title - not time, so resources on the same date are not ordered by time.~~
_Changed sort-date to append hr:min, so it will be ordered by date-time, not date. 
But it will need to be fully reindexed in evening/off-hours to take effect. Makes it easier to test and debug._ 
Do we need alternate output format styled as rss or atom xml, or does search results page work ?

**Comment by sdm7g** [comment] 2021-05-21 18:00
Changed sort option label from "RSS" to "newest" -- less cryptic. 
https://github.com/VAheritage/xtf/commit/3ccf494153ba13741150ffaa22f98e562216b826

**Comment by sdm7g** [comment] 2021-07-05 15:10
@mtkidd  Do you require

**Comment by sdm7g** [comment] 2021-07-05 15:13
@mtkidd  Is fixing the sort to "newest" sufficient, or do you need an additional page formatted as RSS ? 
( I assumed that is what PolitePol is doing for you -- Can I close this ticket ? )

**Comment by mtkidd** [comment] 2021-07-06 13:38
Yes, the sort to newest is all I need. Thanks.

**Closed as completed** 2021-07-06 14:08 UTC
